# This is a basic workflow to help you get started with Actions

name: Automated Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: 
     - master
  workflow_dispatch:
     branches:    
      - master  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "testing"
  testing:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Check for the FreePascal Compiler
      - name: Check for the FreePascal Compiler
        run: sudo apt-get update && apt-cache search fpc

      # Install the FreePascal Compiler
      - name: Install the FreePascal Compiler
        run: sudo apt-get install fpc fp-utils
        
      # Compile the Demo Application
      - name: Compile the Demo Application
        run: /usr/bin/fpc -MObjFPC -Scghi -CX -Cg -O3 -XX -l -vewnhibq -Fi./lib/x86_64-linux -Fu./src -Fu./ -FU./lib/x86_64-linux/ -FE./ -o./demo_hash-lists.run demohashlists.pas
